### PR TITLE
New home for react.force

### PR DESCRIPTION
**Pull request by wmathurin**
@ivanbogdanov

### CODE REVIEW

**Comment by ivanbogdanov** [comment]
should we use react-native-force package name instead? It is more inline with react community naming conventions

**Comment by wmathurin** [comment]
The package name is still react.force (see package.json), but the repo name has changed to be more like the other SalesforceMobileSDK-ReactNative.
The repo name won't matter if we npm package/publish.
At some point we might have more than the javascript in the repo.

**Comment by ivanbogdanov** [comment]
Yes. I am talking about the package name

**Comment by wmathurin** [comment]
Ok so you want react-native-force in package.json instead of react.force?

**Comment by ivanbogdanov** [comment]
Yes

**Comment by wmathurin** [comment]
@ivanbogdanov Sounds good, done here: https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/2/commits/03a71cb9d5495680d9a65ed2c8647d5bdb33e18a

**Comment by wmathurin** [comment]
Also updated template here: https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/2/commits/21fbbd30f30b5678abb4e2c6d4389fdad752ed62

**Pull request merged**
